### ISSUE TITLE
What goes in the config file?

### ISSUE THREAD

**Issue by tlc** [Woody2143/HumbleBundleDL#1]
What goes in the config file?

**Comment by Woody2143** [comment]
Sorry, I realize this script is still super-alpha. And a bigger apology that I didn't see this question till now, Oct 9th, holy smokes! 

The session cookie you can get from your browser when you log in to humble bundle, just look at your cookies. One day I hope to automate it enough it'll take care of the logging in. This is just a side-side project right now, so any code submissions would be awesome.

cat .humbleBundle.cfg
sessionCookie: 'xxxxxxxxxxxxxxx'
saveDir: '/home/jsmith/saves'

**Comment by ekuns** [comment]
I just made a pull request that, among other things, adds documentation about what is expected in the configuration file.

**Comment by Woody2143** [comment]
Cool, I'll look it over and get it merged in!
